### ISSUE TITLE
[Question] Using USB to monitor and send codes 

### ISSUE THREAD

**Issue by ElSaam** [ronoaldo/FlashforgeFinderIntegration#10]
Is is possible to utilize the usb port and drivers to monitor and print from Cura?

I'm no professional or anything and I'm asking so that other people wondering can see the answer here.

**Comment by ronoaldo** [comment]
Hi @ElSaam currently, I don't have support for this but it is planed for the future. I was about to start with wi-fi, which is what I use, but USB basically uses the same communication over a different connection/socket.

**Comment by ElSaam** [comment]
> Hi @ElSaam currently, I don't have support for this but it is planed for the future. I was about to start with wi-fi, which is what I use, but USB basically uses the same communication over a different connection/socket.

Wow that's amazing! Such a good motivation for an uncommon printer.  So glad we have you working on it 😄.
